name: BuildAndTest

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows you to run this workflow on push (merge into main) events
  push:
    branches:
      - 'main'
  # Triggers the workflow when a pull request is created
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Build Action
        uses: ./.github/actions/build