name: Publish

on:
  workflow_dispatch:

jobs:
  publish_google:
    name: "Publish Google Play"
    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up service account key json
        run: |
          echo ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }} | base64 --d > google-billing-service-account-key.json

      - name: Run Build Action
        uses: ./.github/actions/build
        with:
          encoded_keystore: ${{ secrets.KEYSTORE }}
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
          key_password: ${{ secrets.KEY_PASSWORD }}
          keystore_alias: ${{ secrets.KEYSTORE_ALIAS }}

      # Upload build outputs (APKs and AABs)
      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: APKs and AABs
          path: |
            **/build/outputs/apk/**/*.apk
            **/build/outputs/bundle/**/*.aab
            **/build/outputs/mapping/**/*.txt
          retention-days: 1

      # Publish build outputs (AAB) to Google Play
      - name: Publish Release Bundle
        run: |
          ./gradlew publishReleaseBundle --artifact-dir app/build/outputs/bundle/release